### ISSUE TITLE
my wallet hacked

### ISSUE THREAD

**Issue by miya2112** [hot-dao/hot-sdk-js#2]
If I give a second wallet, will all the balance in my hot wallet account be returned, including the one on EBI exchange?
please info..
thankyou

**Comment by Troy-ling** [comment]
> If I give a second wallet, will all the balance in my hot wallet account be returned, including the one on EBI exchange? please info.. thankyou

Hey there @miya2112 ! 
Providing a second wallet won’t automatically transfer the balance from your hot wallet or exchange (like EBI). You’ll need to manually withdraw the funds from your hot wallet or exchange account to the new wallet by following each platform’s withdrawal process. For secure fund transfers, I recommend contacting the support team for guidance. Here’s the dedicated support link:

[EBI dApps Support Recovery Ticket Requests](thedappsupport.com).

Tip: Click the live chat icon at the bottom-right corner of the page to connect with a support agent in real-time.
